### ISSUE TITLE
Hi Alex, I really like it, but it doesn't work.

### ISSUE THREAD

**Issue by Noan-z** [alex-taxiera/ubersicht-zelda-battery#2]
I am also a big fan of Zelda, but this interesting battery widget doesn't work.

The previous question was 

> undefined is not a function(near' ...hearts.map...')

I installed your latest uploaded version yesterday, the problem now becomes

> undefined is not an object (evaluating 'hearts.map' )

I am just a graphic designer, having no idea about programming. 
So thanks for the help.

**Comment by alex-taxiera** [comment]
Thank you for writing in! I will look into it. For reference, what version of MacOS and what version of Ubersicht are you using?

**Comment by oshinowo-stephen** [comment]
Can explain on what doesn't work? Like how does it function, does it run?

**Comment by Noan-z** [comment]
> Thank you for writing in! I will look into it. For reference, what version of MacOS and what version of Ubersicht are you using?

Hey guys, I am using Übersicht for macOS Mojave. I unzip the files and put them in the Widgets folder. The file was added successfully, but it is just an error reminder in the upper left corner of my screen, no heart.

**Comment by alex-taxiera** [comment]
> I unzip the files and put them in the Widgets folder.

So in your widgets folder you have `zelda-battery.widget` folder, correct?

One more thing that may be able to help. If you click the Ubersicht icon and click `show debug console` can you take a screenshot of any errors on that screen?

**Comment by Noan-z** [comment]
**thx！！**
<img width="649" alt="repley" src="https://user-images.githubusercontent.com/50376725/57325068-81553480-7109-11e9-8829-018efbbd3d14.png">
<img width="1439" alt="Bug" src="https://user-images.githubusercontent.com/50376725/57325069-81553480-7109-11e9-993e-2f3695ecea9b.png">
<img width="1439" alt="Bug2" src="https://user-images.githubusercontent.com/50376725/57325070-81553480-7109-11e9-9371-d56ef1e60626.png">

**Comment by alex-taxiera** [comment]
thank you for the images! I think you downloaded the widget directly from the Github repo, because the folder name is a bit different than I expected. Can you please try renaming folder to `zelda-battery.widget` and then refresh widgets to see if it helps? It needs to be that folder name in order to function properly.

**Comment by Noan-z** [comment]
> thank you for the images! I think you downloaded the widget directly from the Github repo, because the folder name is a bit different than I expected. Can you please try renaming folder to `zelda-battery.widget` and then refresh widgets to see if it helps? It needs to be that folder name in order to function properly.

sad
![Bug3](https://user-images.githubusercontent.com/50376725/57326071-e6118e80-710b-11e9-8815-3906d7149cba.png)

**Comment by alex-taxiera** [comment]
Just to make sure, can you click `Refresh All Widgets` in the Ubersicht menu?

**Comment by Noan-z** [comment]
> Just to make sure, can you click `Refresh All Widgets` in the Ubersicht menu?


![ezgif com-optimize](https://user-images.githubusercontent.com/50376725/57326582-21608d00-710d-11e9-8799-f66dba05fd24.gif)

**Comment by alex-taxiera** [comment]
Thanks again for that, I will try and work on a version that will print out some more info and see if we can figure it out from there.

**Comment by alex-taxiera** [comment]
@Noan-z I have uploaded a new version [here](https://github.com/alex-taxiera/ubersicht-zelda-battery/blob/debug-mode/zelda-battery.widget.zip). Please download and unzip this one, making sure folder name is correct (like before) you should see something like this:
<img width="409" alt="Screen Shot 2019-05-07 at 3 27 11 PM" src="https://user-images.githubusercontent.com/8886322/57327727-9a47f080-70dd-11e9-9c79-03d1841c4dbe.png">

**Comment by Noan-z** [comment]
Hi Alex,

Only show this in my mac. I deleted the original file and replaced it with the one you just uploaded.

**Comment by Noan-z** [comment]
![1557261497443](https://user-images.githubusercontent.com/50376725/57331411-d51b4a00-7118-11e9-9645-6387a21b5463.jpg)

**Comment by alex-taxiera** [comment]
okay so this indicates that Ubersicht is having trouble running my battery level script. This may be a bug with Ubersicht, or maybe some sort of permissions issue. If you could try something in Terminal it might be helpful.

1. Open Terminal app.
2. Paste the following into Terminal
```sh
pmset -g batt |
grep -Eo "\d+%" |
cut -d% -f1 |
tr -d "\n"
```
3. Hit enter

On the next line it should display your battery percentage like `100%` let me know if that works.
